[package]
name = "csv-diff-splitter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.2.20"
serde = "1.0.144"
serde_json = "1.0.85"
csv = "1.1.6"
pretty_env_logger = "0.4.0"
stopwatch = "0.0.7"